config/routes.rb
Io::Application.routes.draw do

  match '/login' => 'session#new', :via => :get
  match '/login' => 'session#create', :via => :post
  match '/logout' => 'session#destroy', :via => :delete
  
  resources :users
  resources :tags
  resources :links
  resources :notes
  resources :books

  root :to => 'home#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :name
  has_and_belongs_to_many :tags

  def self.persist(data = {})
    return nil if !data.is_a?(Hash)

    id = Scrub.str(data[:id], '', squish:true)
    name = Scrub.str(data[:name], 'book', minify:true)
    tag_ids = data[:tag_ids].is_a?(Array) ? data[:tag_ids] : []

    obj = Book.find_by_id(id) || Book.find_or_create_by_name(name)
    obj.tags = tag_ids.map{|n| Tag.find_by_id(n)}.compact.uniq
    obj.update_attributes(name:name)
    obj
  end
  
end

app/models/link.rb
class Link < ActiveRecord::Base
  has_and_belongs_to_many :tags

  def self.persist(data = {})
    return nil if !data.is_a?(Hash)
    
    id = data[:id]
    url = data[:url]
    title = data[:title]
    tags = data[:tags]
    
    return nil if [id, url, title, tags].any?{|v| v.class != String}
    
    id = id.squish
    url = url.present? ? url.squish : "default"
    title = title.present? ? title.squish : "default"
    tags = tags.present? ? tags.squish.split : ["default"]

    obj = Link.find_by_id(id) || Link.find_or_create_by_url(url)

    obj.url = url
    obj.title = title
    obj.tags = tags.map{|n| Tag.persist({:id => "", :name => n})}.compact.uniq
    obj.save

    obj
  end
end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :info
  has_and_belongs_to_many :tags

  def self.persist(data = {})
    return nil if !data.is_a?(Hash)

    id = Scrub.str(data[:id], '', squish:true)
    info = Scrub.str(data[:info], 'info')
    tags = Scrub.str(data[:tags], 'tag', squish:true)

    obj = Note.find_by_id(id) || Note.create(info:info)
    obj.tags = tags.split.map{|n| Tag.persist(name:n)}.compact.uniq
    obj.update_attributes(info:info)
    obj
  end
end

app/models/scrub.rb
class Scrub

  def self.str(s, default, options={})
    return default if !s.is_a?(String)
    s = s.presence || default
    s = s.strip if options[:strip]
    s = s.squish if options[:squish]
    s = s.squish.downcase if options[:minify]
    s = yield(s) if block_given?
    s
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name
  has_and_belongs_to_many :links
  has_and_belongs_to_many :books
  has_and_belongs_to_many :notes

  def self.persist(data = {})
    return nil if !data.is_a?(Hash)

    id = Scrub.str(data[:id], '', squish:true)
    name = Scrub.str(data[:name], 'tag', minify:true)

    obj = Tag.find_by_id(id) || Tag.find_or_create_by_name(name)
    obj.update_attributes(name:name)
    obj
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate
  private
  def authenticate
  if session[:user_id]
    @auth = User.find(session[:user_id])
  else
    @auth = nil
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  layout 'arc'
  def new
    @book = Book.new
  end
  
  def create
    Book.persist(params[:book])
    redirect_to books_path
  end
  
  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    Book.persist(params[:book])
    redirect_to books_path
  end
  
  def show
    @book = Book.find(params[:id])
  end
  
  def index
    @books = Book.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  layout 'arc'
  def new
    @link = Link.new
  end
  
  def create
    Link.persist(params[:link])
    redirect_to tags_path
  end
  
  def edit
    @link = Link.find(params[:id])
  end
  
  def update
    Link.persist(params[:link])
    redirect_to tags_path
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  layout 'arc'
  def new
    @note = Note.new
  end
  
  def create
    Note.persist(params[:note])
    redirect_to tags_path
  end
  
  def edit
    @note = Note.find(params[:id])
  end
  
  def update
    Note.persist(params[:note])
    redirect_to tags_path
  end
  
  def show
    @note = Note.find(params[:id])
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  layout 'arc'
  def new
  end
  
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to tags_path
    else
      redirect_to login_path
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to tags_path
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  layout 'arc'
  def index
    @tags = Tag.find(:all, :order => :name)
  end
  
  def edit
    @tag = Tag.find(params[:id])
  end
  
  def update
    Tag.persist(params[:tag])
    redirect_to tags_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'arc'
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

def show_book_link(book)
  if book.try(:persisted?)
    link_to book.name, edit_book_path(book), :class => 'bookname'
  end
end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, :autofocus => 'autofocus' %>
  </div>

  <% Tag.all.each do |tag| %>
    <%= tag.name %>
    <%= check_box_tag 'book[tag_ids][]', tag.id, @book.tags.include?(tag) %>
  <% end %>

  <div class="actions">
	<%= f.hidden_field :id, :value => @book.id %>
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<%= form_for(@book) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

	<% Tag.all.each do |tag| %>
		<%= tag.name %>
		<%= check_box_tag 'book[tag_ids][]', tag.id, @book.tags.include?(tag) %>
	<% end %>

  <div class="actions">
	<%= f.hidden_field :id, :value => @book.id %>
    <%= f.submit %>
  </div>
<% end %>

app/views/books/index.html.erb
<% @books.each do |book| %>
	<div class="book">
		<%= link_to book.name, book_path(book) %>
	</div>
<% end %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<%= render :partial => 'shared/tag', :collection => @book.tags, :as => :tag %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>chyld.io</title>
  <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="main">
	<div id="header"><%= image_tag('chyld.jpg') %></div>
	<div id="motto">:i_create_software_engineers => {manhattan, brooklyn, queens}</div>
	<div id="nav">
		<div class="link"><%= link_to 'iOS', '/' %></div>
		<div class="link"><%= link_to 'Objective-C', '/' %></div>
		<div class="link"><%= link_to 'Ruby', '/' %></div>
		<div class="link"><%= link_to 'Rails', '/' %></div>
		<div class="link"><%= link_to 'Node.js', '/' %></div>
		<div class="link"><%= link_to 'JavaScript', '/' %></div>
		<div class="link"><%= link_to 'jQuery', '/' %></div>
		<div class="link"><%= link_to 'Git', '/' %></div>
		<div class="link"><%= link_to 'TDD', '/' %></div>
		<div class="link"><%= link_to 'Algorithms', '/' %></div>
		<div class="link"><%= link_to 'HTML 5', '/' %></div>
		<div class="link"><%= link_to 'CSS 3', '/' %></div>
		<div class="clear"></div>
	</div>
	<div id="content"><%= yield %></div>
	<div id="footer">(c) Chyld Medford, 2012</div>
</div>

</body>
</html>

app/views/layouts/arc.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>chyld.io</title>
  <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
  <%= stylesheet_link_tag    "arc", :media => "all" %>
  <%= javascript_include_tag "arc" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <ul class="nav">
	  <li><a href="<%= root_path %>">Home</a></li>
		<li><a href="<%= tags_path %>">Tags</a></li>
		<li><a href="<%= books_path %>">Books</a></li>
		<li><a href="<%= new_link_path %>">*link</a></li>
		<li><a href="<%= new_note_path %>">*note</a></li>
		<li><a href="<%= new_book_path %>">*book</a></li>
		<li><%= show_book_link(@book) %></li>
	</ul>
	<%= yield %>

</body>
</html>

app/views/layouts/links.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>chyld.io</title>
  <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
  <%= stylesheet_link_tag    "links", :media => "all" %>
  <%= javascript_include_tag "links" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="nav">
		<%= link_to "i/o", root_path %>
		::
		<%= link_to "Books", books_path %>
		::
		<%= link_to "Links", links_path %>
		::
		<%= link_to "*book", new_book_path %>
		::
		<%= link_to "*link", new_link_path %>
		::
		<%= show_book_link(@book) %>
	</div>

	<div class="content"><%= yield %></div>

</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_area :title, :autofocus => 'autofocus', :rows => 3 %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_area :url, :rows => 3 %>
  </div>
  <div class="field">
    <%= f.label :tags %><br />
    <%= f.text_area :tags, :value => @link.tags.map(&:name).join(' '), :rows => 3 %>
  </div>
  <div class="actions">
		<%= f.hidden_field :id, :value => @link.id %>
    <%= f.submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/new.html.erb
<h1>New link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <div class="field">
    <%= f.label :info %><br />
    <%= f.text_area :info, :autofocus => 'autofocus', :rows => 3 %>
  </div>
  <div class="field">
    <%= f.label :tags %><br />
    <%= f.text_area :tags, :value => @note.tags.map(&:name).join(' '), :rows => 3 %>
  </div>
  <div class="actions">
	<%= f.hidden_field :id, :value => @note.id %>
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<div class="info">
	<%= @note.info.gsub("\n", '<br />').html_safe %>
</div>

app/views/session/new.html.erb
<%= form_tag do %>
  <%= text_field_tag 'email' %>
  <%= password_field_tag 'password' %>
  <%= submit_tag 'Login' %>
<% end %>

app/views/shared/_tag.html.erb
<div class="tag">
	<div class="tagname"><%= link_to tag.name, edit_tag_path(tag) %></div>
	<div class="data">
		<% tag.links.each do |link| %>
			<div class="link">
				<%= link_to "-".html_safe, edit_link_path(link) %>
				<%= link_to link.title.truncate(60), link.url, :target => '_blank' %>
			</div>
		<% end %>
		<% tag.notes.each do |note| %>
			<div class="note">
				<%= link_to "+".html_safe , edit_note_path(note) %>
				<%= link_to note.info.truncate(60), note_path(note) %>
			</div>
		<% end %>
	</div>
</div>

app/views/tags/edit.html.erb
<%= form_for(@tag) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, :autofocus => 'autofocus' %>
  </div>
  <div class="actions">
	<%= f.hidden_field :id, :value => @tag.id %>
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/index.html.erb
<%= render :partial => 'shared/tag', :collection => @tags, :as => :tag %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Email</th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>